### ISSUE TITLE
你好，这个项目我下载编译后，为什么无法进行游戏呢

### ISSUE THREAD

**Issue by peterwangx** [qq456cvb/doudizhu-baseline#1]

**Comment by qq456cvb** [comment]
编译main.cpp，跑main 函数 会进行模拟对局和打印胜负统计。

**Comment by peterwangx** [comment]
&nbsp;&nbsp;&nbsp; //int total = argc &gt; 1 ? atoi(argv[1]) : 1000;
&nbsp;&nbsp;&nbsp; //n_threads = argc &gt; 2 ? atoi(argv[2]) : 8;
&nbsp;&nbsp;&nbsp; //max_d = argc &gt; 3 ? atoi(argv[3]) : 50;
&nbsp;&nbsp;&nbsp; //max_iter = argc &gt; 4 ? atoi(argv[4]) : 250;
&nbsp;&nbsp;&nbsp; int total = argc &gt; 1 ? atoi(argv[1]) : 2;
&nbsp;&nbsp;&nbsp; n_threads = argc &gt; 2 ? atoi(argv[2]) : 4;
&nbsp;&nbsp;&nbsp; max_d = argc &gt; 3 ? atoi(argv[3]) : 10;
&nbsp;&nbsp;&nbsp; max_iter = argc &gt; 4 ? atoi(argv[4]) : 20;

为了缩减时间，我把训练的次数减少了，目的是希望能快速的玩游戏进行测试，但是我模拟完对局后，不知道怎么才能和机器对玩。
下面是模拟输出结果：

seeding 2395931730
2, 0 [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||]&nbsp; 0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neil You"<notifications@github.com&gt;; 
发送时间: 2020年8月1日(星期六) 晚上9:58
收件人: "qq456cvb/doudizhu-baseline"<doudizhu-baseline@noreply.github.com&gt;; 
抄送: "hywood"<luoqian126@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [qq456cvb/doudizhu-baseline] 你好，这个项目我下载编译后，为什么无法进行游戏呢 (#1)





 
编译main.cpp，跑main 函数 会进行模拟对局和打印胜负统计。

**Comment by qq456cvb** [comment]
目前这个是用来测试AI之间对打的，你可以自己拓展一下Player这个类的respond函数，来从命令行读取出牌操作。
